apiVersion: apps/v1
kind: Deployment
metadata:
  name: idasen-restapi-microservice-desk
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: idasen-restapi-microservice-desk
  replicas: 1
  template:
    metadata:
      labels:
        app: idasen-restapi-microservice-desk
    spec:
      containers:
      - name: idasen-restapi-microservice-desk
        image: ajoebcool/idasenrestapimicroservicedesk
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
        resources:
            requests:
                memory: "500Mi"
                cpu: "10m"
            limits:
                memory: "1000Mi"
                cpu: "100m"