apiVersion: v1
kind: Service
metadata:
  name: idasen-restapi-microservice-desk-height
  namespace: default
  labels:
    app: idasen-restapi-microservice-desk-height
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    app: idasen-restapi-microservice-desk-height
  type: ClusterIP