apiVersion: v1
kind: Service
metadata:
  name: idasen-restapi-external-desk
  namespace: default
  labels:
    app: idasen-restapi-external-desk
spec:
  ports:
  - name: http
    port: 5080
    protocol: TCP
    targetPort: 5080
  selector: {}