apiVersion: apps/v1
kind: Deployment
metadata:
  name: idasen-restapi-desk
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: idasen-restapi-desk
  replicas: 1 
  template: 
    metadata:
      labels:
        app: idasen-restapi-desk
    spec:
      containers:
      - name: idasen-restapi-desk
        image: ajoebcool/idasenrestapidesk
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5

      #- image: ajoebcool/idasenrestapimicroservicedesk
